pub mod elitist_selection_oneplusfour;
pub mod elitist_selection_mupluslambda;
// pub mod tournament_selection;
pub mod elitist_selection_tournament;
pub mod elitist_selection_mucommalambda;
pub mod elitist_selection_saga4_random;
pub mod elitist_selection_saga4_parent_tournament;
pub mod elitist_selection_saga4_survivor_tournament;
pub mod selection_saga4_full;
pub mod selection_trait;
pub mod selection_types;